### PR TITLE
Procedurally generate the inputrc files

### PR DESCRIPTION
**Pull request by GarkGarcia**
This is a follow up to https://github.com/Mathics3/mathicsscript/pull/16#discussion_r564493237. I've noticed there are yet more errors in the translation tables (in the ESC alias column specifically). I'll go over those before we merge this.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
> I've noticed there are yet more errors in the translation tables (in the ESC alias column specifically). I'll go over those before we merge this.

I've fixed the ones I could find in https://github.com/Mathics3/mathics-scanner/commit/fd335e71480b35f9d1860b8f42f84cc2828ba1de.

**Comment by GarkGarcia** [comment]
@rocky I don't know whats the best place to run the code that generates the files, feel free to change it if you feel like so.

**Review by rocky — COMMENTED** [review]
Redone now that the inputrc generation file has moved to mathics-scanner

**Comment by rocky** [comment]
Has been merged via rc1 into master.

**Pull request closed without merging**
