### PR TITLE
Add option Settings`$GroupAutocomplete to disable autobracing.

### LINKED ISSUE #55: Is there an option to disable Mathics autoclosing parentheses?
I'm willing to work on this.

### PR DESCRIPTION
**Pull request by DUOLabs333**
Fixes #55

### CODE REVIEW

**Comment by rocky** [comment]
Please add a default setting and description of the option to [settings.m](https://github.com/Mathics3/mathicsscript/blob/master/mathicsscript/autoload/settings.m)

**Comment by rocky** [comment]
From #55 
> However, the PR does break the ability for me to type in }. ..

If this is still the case let's hold off until that is addressed.

**Review by rocky — CHANGES_REQUESTED** [review]
See and follow the requests made and suggestions given.

For example: https://github.com/Mathics3/mathicsscript/issues/55#issuecomment-1032920908

**Comment by DUOLabs333** [comment]
@rocky There's an issue with it, so I'm going to try to fix it before finishing up.

**Comment by DUOLabs333** [comment]
In `bindkey.py`, why are there bindings for the right brackets? Aren't there only supposed to be defined for the left?

**Comment by rocky** [comment]
Will try to look at this over the next weekend.

**Review by rocky — APPROVED** [review]
Looks good now - thanks. Black formatting is failing. So I fixed this in another branch forked off of this which I will merge.

**Comment by rocky** [comment]
Merged via #60. Thanks for the PR.

**Pull request closed without merging**
